#!/bin/bash
if [ -z $1 ]; then
echo "Uso: tcx-s [opciones] archivo..."
echo "Opciones:"
echo "-f: Archivo a ejecutar."
echo "-i: Modo de editor (se requiere -o)."
echo "-o: Archivo de salida del editor (se requiere -i)."
echo "-s: Abrir el interpréte."
elif [ -n $1 ] && [ -n $2 ] && [ $1 = "-f" ]; then
if  [ -f $2 ]; then
tcx $2
else
echo "ERROR no se pudo encontrar el archivo."
fi
elif [ -n $1 ] && [ -n $2 ] && [ -n $3 ] && [ $1 = "-i" ] && [ $2 = "-o" ]; then
for i in `seq 1 1000`;
do
	read -p ">> " input
	echo "#!/bin/tcx" >> $3
	echo $input >> $3
done
elif [ -n $1 ] && [ $1 = "-s" ]; then
for i in `seq 1 100000`;
do
	read -p ">> " input
	echo "#!/bin/tcx" >> $HOME/.tcx-history.tcx
	echo $input >> $HOME/.tcx-history.tcx
	tcx $HOME/.tcx.tcx
done
elif [ -n $1 ] && [ $1 = "-h" ]; then
echo "Uso: tcx-s [opciones] archivo..."
echo "Opciones:"
echo "-f: Archivo a ejecutar."
echo "-i: Modo de editor (se requiere -o)."
echo "-o: Archivo de salida del editor (se requiere -i)."
echo "-s: Abrir el interpréte."
else
echo "ERROR opción no reconocida, pruebe '-h' para más información."
fi